categories:
  partnerrating: ~
  partnerrating.templates:
    parent: partnerrating
  partnerrating.resources:
    parent: partnerrating
  partnerrating.settings:
    parent: partnerrating

settings:
  plugin.tx_partnerrating_pi1.view.templateRootPath:
    type: string
    default: 'EXT:partner_rating/Resources/Private/Templates/'
    category: partnerrating.templates
  plugin.tx_partnerrating_pi1.view.partialRootPath:
    type: string
    default: 'EXT:partner_rating/Resources/Private/Partials/'
    category: partnerrating.templates
  plugin.tx_partnerrating_pi1.view.layoutRootPath:
    type: string
    default: 'EXT:partner_rating/Resources/Private/Layouts/'
    category: partnerrating.templates
  plugin.tx_partnerrating_pi1.settings.includeBootstrap:
    type: bool
    default: 0
    category: partnerrating.resources
  plugin.tx_partnerrating_pi1.settings.cssFile:
    type: string
    default: 'EXT:partner_rating/Resources/Public/Css/main.min.css'
    category: partnerrating.resources
  plugin.tx_partnerrating_pi1.settings.javaScriptFile:
    type: string
    default: 'EXT:partner_rating/Resources/Public/JavaScript/show.min.js'
    category: partnerrating.resources
  plugin.tx_partnerrating_pi1.settings.ratingValues:
    type: stringlist
    default:
      - 1
      - 2
      - 3
      - 4
      - 5
    category: partnerrating.settings
  plugin.tx_partnerrating_pi1.settings.ratingReasonMinValue:
    type: int
    default: 3
    category: partnerrating.settings
  plugin.tx_partnerrating_pi1.settings.ratingMailMinValue:
    type: int
    default: 4
    category: partnerrating.settings
  plugin.tx_partnerrating_pi1.settings.keepMinOneSearchResult:
    type: bool
    default: 1
    category: partnerrating.settings
  plugin.tx_partnerrating_pi1.settings.partnerLabelFields:
    type: stringlist
    default:
      - title
      - partner_nr
    category: partnerrating.settings
  plugin.tx_partnerrating_pi1.settings.mail.subject:
    type: string
    default: ''
    category: partnerrating.settings
  plugin.tx_partnerrating_pi1.settings.mail.from:
    type: string
    default: ''
    category: partnerrating.settings
  plugin.tx_partnerrating_pi1.settings.mail.to:
    type: string
    default: ''
    category: partnerrating.settings
