services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ErHaWeb\PartnerRating\:
    resource: '../Classes/*'

  ErHaWeb\PartnerRating\Event\Listener\SiteConfigurationLoadedEventListener:
    tags:
      - name: event.listener
        identifier: 'ext-partnerrating/site-configuration-loaded'
        event: TYPO3\CMS\Core\Configuration\Event\SiteConfigurationLoadedEvent
